services:
  bot:
    image: mirosensei/ur-vacancy-bot:latest
    container_name: ur-vacancy-bot
    restart: unless-stopped
    volumes:
      - ./config.json:/app/config.json
      - ./state.json:/app/state.json
      - ./logs:/app/logs
    environment:
      - TZ=Asia/Tokyo
